-- MySQL Script generated by MySQL Workbench
-- Thu Sep 28 10:27:47 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbfirst
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbfirst
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbfirst` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `dbfirst` ;

-- -----------------------------------------------------
-- Table `dbfirst`.`reiziger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfirst`.`reiziger` (
  `reizigerID` INT UNSIGNED NOT NULL,
  `naam` VARCHAR(45) NOT NULL,
  `reizigercol` VARCHAR(45) NOT NULL,
  `bestemming` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`reizigerID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbfirst`.`taxi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfirst`.`taxi` (
  `idtaxi` INT UNSIGNED NOT NULL,
  `capiciteit` INT NOT NULL,
  `aankomst tijd` TIME NOT NULL,
  `taxicol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idtaxi`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
